package com.account.domain.ledger;

public enum LedgerGroupType {

    BRANCH_DIVISIONS,
    CAPITAL_ACCOUNT,
    CURRENT_ASSETS,
    CURRENT_LIABILITIES,
    DIRECT_EXPENSES,
    DIRECT_INCOMES,
    FIXED_ASSETS,
    INDIRECT_EXPENSES,
    INDIRECT_INCOMES,
    INVESTMENTS,
    LOANS_LIABILITY,
    MISC_EXPENSES_ASSET,
    PURCHASE_ACCOUNTS,
    SALES_ACCOUNTS,
    SUSPENSE_ACCOUNT,
    BANK_ACCOUNTS,
    BANK_OD_ACCOUNT,
    CASH_IN_HAND,
    DEPOSITS_ASSET,
    DUTIES_AND_TAXES,
    LOANS_AND_ADVANCES_ASSET,
    PROVISIONS,
    RESERVES_AND_SURPLUS,
    SECURED_LOANS,
    STOCK_IN_HAND,
    SUNDRY_CREDITORS,
    SUNDRY_DEBTORS,
    UNSECURED_LOANS
}